### ISSUE TITLE
Feature Request: HTTP and SOCKS5 Proxy

### ISSUE THREAD

**Issue by Taherismail17** [ChengLuffy/ShadowsocksFree#2]

**Comment by ChengLuffy** [comment]
I cann't find free HTTP and SOCKS5 proxys, but [NEKit](https://github.com/zhuhaow/NEKit) / [libnekit](https://github.com/zhuhaow/libnekit) support HTTP and SOCKS5 settings

**Comment by Taherismail17** [comment]
Hey, I can find socks5 and http proxies but I am having issues putting into an app? I don't know how to make it connect, it doesn't work for me.

**Comment by jettangtzj** [comment]
Hi, I use the same config with ss server. project yichengchen/RabbitVpnDemo works fine, but this project cannot connect, I checked all the code still don't know why.

**Comment by ChengLuffy** [comment]
@Taherismail17  supported.
dd893f6a63b8c1d23476a87b4135af3c88ec5d2e
