### ISSUE TITLE
你好,请问一下是不是要有Network Extetion框架权限才能编译到真机?

### ISSUE THREAD

**Issue by sushushu** [ChengLuffy/ShadowsocksFree#3]
我已经把BundleID都改掉了,
出现错误提示:
Your development team, "He JinWei", does not support the Personal VPN and Network Extensions capabilities.
所以想请问一定要有Network Extetion框架权限才能编译到真机啊?

**Comment by ChengLuffy** [comment]
>我已经把BundleID都改掉了, ...

@sushushu 只要是交过 99 刀的开发者账号，都可以成功编译，Apple 已经开放了 NE 权限。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sushushu** [comment]
已经解决 谢谢
